# Generated by Django 4.1.3 on 2023-01-22 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='brand',
            name='articles_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='number_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('SKI', 'SKI'), ('BOOTS', 'SKI_BOOTS'), ('POLES', 'SKI_POLES'),
                                            ('HELMET', 'HELMET'), ('GOGGLES', 'GOGGLES'), ('SNOWBOARD', 'SNOWBOARD')],
                                   default='SKI', max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_orders', models.IntegerField(default=0)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(default='', max_length=130)),
                ('article_price', models.IntegerField(default=0)),
                ('delivery', models.BooleanField(default=False)),
                ('order_address', models.CharField(default='', max_length=150)),
                ('number_of_articles', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                               to='strona.profile')),
            ],
        ),
    ]
