# Generated by Django 4.1.3 on 2023-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0002_article_image_brand_articles_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('SI', 'SKI'), ('TS', 'SKI_BOOTS'), ('POLES', 'SKI_POLES'), ('HEL', 'HELMET'), ('GOGG', 'GOGGLES'), ('SNOARD', 'SNOWBOARD')], default='SI', max_length=10),
        ),
    ]
