# Generated by Django 4.1.3 on 2023-01-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona', '0003_alter_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('SKI', 'SKI'), ('BOOTS', 'SKI_BOOTS'), ('POLES', 'SKI_POLES'), ('HELMET', 'HELMET'), ('GOGGLES', 'GOGGLES'), ('SNOWBOARD', 'SNOWBOARD')], default='SKI', max_length=10),
        ),
    ]
